OficinaWeb/Models/MyServicesViewModel.cs
using OficinaWeb.Data.Entities;
using System.Collections.Generic;

namespace OficinaWeb.Models
{
    public class MyServicesViewModel
    {
        public List<RepairAndServices> MyServices { get; set; } 

    }
}

OficinaWeb/Models/RepairAndServicesViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using OficinaWeb.Data.Entities;
using System.Collections.Generic;

namespace OficinaWeb.Models
{
    public class RepairAndServicesViewModel : RepairAndServices
    {
        public SelectList ServiceTypes { get; set; } 
    }
}

OficinaWeb/Controllers/PartsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using OficinaWeb.Data;
using OficinaWeb.Data.Entities;
using OficinaWeb.Helpers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace OficinaWeb.Controllers
{
    public class PartsController : Controller
    {
        private readonly DataContext _context;
        private readonly IPartsRepository _partsRepository;
        private readonly IRepairAndServicesRepository _repairAndServicesRepository;

        public PartsController(
            DataContext context,
            IPartsRepository partsRepository,
            IRepairAndServicesRepository repairAndServicesRepository)
        {
            _context = context;
            _partsRepository = partsRepository;
            _repairAndServicesRepository = repairAndServicesRepository;
        }

        // GET: Parts
        public async Task<IActionResult> Index(int? serviceId )
        {
            var serviceExists = await  _repairAndServicesRepository.ExistsAsync(serviceId.Value);

            if (serviceId == null || !serviceExists)
            {
                return NotFound();
            }

            
            ViewBag.ServiceId = serviceId;

            var parts = await _partsRepository
           .GetAll()
           .Where(p => p.RepairAndServicesId == serviceId.Value)
           .OrderBy(p => p.Name)
           .ToListAsync();


            return View(parts);                                             
        }

        // GET: Parts/Details/5
        public async Task<IActionResult> Details(int? id, int serviceId)
        {
            if (id == null)
            {
                return new NotFoundViewResult("PartNotFound");
            }

            var serviceExists = await _repairAndServicesRepository.ExistsAsync(serviceId);

            if (!serviceExists)
            {
                return NotFound();
            }

            ViewBag.ServiceId = serviceId;

            var part = await _partsRepository.GetWithIncludesAsync(id.Value);
            if (part == null)
            {
                return new NotFoundViewResult("PartNotFound");
            }

            return View(part);
        }

        // GET: Parts/Create
        public async Task<IActionResult> Create(int? serviceId)
        {

            var serviceExists = await _repairAndServicesRepository.ExistsAsync(serviceId.Value);

            if (serviceId == null || !serviceExists)
            {
                return NotFound();
            }

            ViewBag.ServiceId = serviceId;
          
            return View();
        }

        // POST: Parts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create( Part part)
        {
            if (ModelState.IsValid)
            {
                await _partsRepository.CreateAsync(part);
                return RedirectToAction("Index", new { serviceId = part.RepairAndServicesId });
            }
           
            return View(part);
        }

        // GET: Parts/Edit/5
        public async Task<IActionResult> Edit(int? id, int serviceId)
        {
            var serviceExists = await _repairAndServicesRepository.ExistsAsync(serviceId);

            if (!serviceExists)
            {
                return NotFound();
            }

            if (id == null)
            {
                return new NotFoundViewResult("PartNotFound");
            }

            ViewBag.ServiceId = serviceId;

            var part = await _partsRepository.GetWithIncludesAsync(id.Value);
            if (part == null)
            {
                return new NotFoundViewResult("PartNotFound");
            }
           
            return View(part);
        }

        // POST: Parts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Part part)
        {
            if (id != part.Id)
            {
                return new NotFoundViewResult("PartNotFound");
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await _partsRepository.CreateAsync(part); 
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (! await _partsRepository.ExistsAsync(id))
                    {
                        return new NotFoundViewResult("PartNotFound");
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index", new { serviceId = part.RepairAndServicesId });
            }
           
            return View(part);
        }

        // GET: Parts/Delete/5
        public async Task<IActionResult> Delete(int? id, int serviceId)
        {
            var serviceExists = await _repairAndServicesRepository.ExistsAsync(serviceId);

            if (!serviceExists)
            {
                return NotFound();
            }

            if (id == null)
            {
                return new NotFoundViewResult("PartNotFound");
            }

            ViewBag.ServiceId = serviceId;

            var part = await _partsRepository.GetWithIncludesAsync(id.Value);
            if (part == null)
            {
                return new NotFoundViewResult("PartNotFound");
            }

            return View(part);
        }

        // POST: Parts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var part = await _partsRepository.GetWithIncludesAsync(id);
            await _partsRepository.DeleteAsync(part);
            return RedirectToAction("Index", new { serviceId = part.RepairAndServicesId });
        }

       


        public IActionResult PartNotFound()
        {
            return View();
        }
    }
}

OficinaWeb/Controllers/RepairAndServicesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using OficinaWeb.Data;
using OficinaWeb.Data.Entities;
using OficinaWeb.Helpers;
using OficinaWeb.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;

namespace OficinaWeb.Controllers
{
    public class RepairAndServicesController : Controller
    {
        private readonly DataContext _context;
        private readonly IRepairAndServicesRepository _repairAndServicesRepository;
        private readonly IMechanicRepository _mechanicRepository;
        private readonly IServiceTypeRepository _serviceTypeRepository;
        private readonly IClientRepository _clientRepository;
        private readonly IConverterHelper _converterHelper;
        private readonly IVehicleRepository _vehicleRepository;

        public RepairAndServicesController(
            DataContext context,
            IRepairAndServicesRepository repairAndServicesRepository,
            IMechanicRepository mechanicRepository,
            IServiceTypeRepository serviceTypeRepository,
            IClientRepository clientRepository,
            IConverterHelper converterHelper,
            
            IVehicleRepository vehicleRepository
             )
        {
            _context = context;
            _repairAndServicesRepository = repairAndServicesRepository;
            _mechanicRepository = mechanicRepository;
            _serviceTypeRepository = serviceTypeRepository;
            _clientRepository = clientRepository;
            _converterHelper = converterHelper;
            _vehicleRepository = vehicleRepository;
        }

        // GET: RepairAndServices
        public  IActionResult Index()
        {
            return View(_repairAndServicesRepository
                .GetAll()
                .Where(r => r.EndDate > DateTime.Now)
                .Include(r => r.Client)
                .Include(r => r.Vehicle)
                .Include(r => r.Vehicle.CarBrand)
                .Include(r => r.Vehicle.CarModel)
                .Include(r => r.Mechanics)
                .Include(r => r.ServiceType)
                .OrderBy(r => r.BeginDate));
        }

        // GET: RepairAndServices/Details/5
        public async Task<IActionResult> Details(int? id, bool fromMyServices = false, int? vehicleId = null)
        {
            if (id == null)
            {
                return new NotFoundViewResult("ServiceNotFound");
            }

            var repairAndServices = await _repairAndServicesRepository.GetWithIncludesAsync(id.Value);
            if (repairAndServices == null)
            {
                return new NotFoundViewResult("ServiceNotFound");
            }

            ViewData["FromMyServices"] = fromMyServices;
            ViewData["VehicleId"] = vehicleId;



            return View(repairAndServices);
        }

        // GET: RepairAndServices/Create
        public IActionResult Create()
        {
            var model = new RepairAndServicesViewModel();
            

            var serviceTypes = _serviceTypeRepository.GetAll().ToList();
            model.ServiceTypes = new SelectList(serviceTypes, "Id","Name");



            return View(model);
        }

        // POST: RepairAndServices/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(RepairAndServicesViewModel model)
        {
            if (model.EndDate < DateTime.Today)
            {
                ModelState.AddModelError(nameof(model.EndDate), "End date cannot be in the past.");
            }

            if (model.EndDate <= model.BeginDate)
            {
                ModelState.AddModelError(nameof(model.EndDate), "End date must be after the begin date.");
            }

            if (model.BeginDate < DateTime.Today)
            {
                ModelState.AddModelError(nameof(model.BeginDate), "Begin date cannot be in the past.");
            }


            if (ModelState.IsValid)
            {
                var repairAndServices = _converterHelper.ToRepairAndServices(model, true);

                await _repairAndServicesRepository.CreateAsync(repairAndServices);

                await _repairAndServicesRepository.AddMechanics(repairAndServices.Id, repairAndServices.MechanicIds);
                

                return RedirectToAction("Index");
            }            

            var serviceTypes = _serviceTypeRepository.GetAll().ToList();
            model.ServiceTypes = new SelectList(serviceTypes, "Id", "Name");


            return View(model);
        }







        // GET: RepairAndServices/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new NotFoundViewResult("ServiceNotFound");
            }

            var repairAndServices = await _repairAndServicesRepository.GetWithIncludesAsync(id.Value);
            if (repairAndServices == null)
            {
                return new NotFoundViewResult("ServiceNotFound");
            }

            var model = _converterHelper.ToRepairAndServicesViewModel(repairAndServices);

            var serviceTypes = _serviceTypeRepository.GetAll().ToList();
            model.ServiceTypes = new SelectList(serviceTypes, "Id", "Name");



            return View(model);
        }

        // POST: RepairAndServices/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, RepairAndServices repairAndServices)
        {

           

            if (id != repairAndServices.Id)
            {
                return new NotFoundViewResult("ServiceNotFound");
            }

            if (repairAndServices.EndDate < DateTime.Today)
            {
                ModelState.AddModelError(nameof(repairAndServices.EndDate), "End date cannot be in the past.");
            }

            if (repairAndServices.EndDate <= repairAndServices.BeginDate)
            {
                ModelState.AddModelError(nameof(repairAndServices.EndDate), "End date must be after the begin date.");
            }

            if (repairAndServices.BeginDate < DateTime.Today)
            {
                ModelState.AddModelError(nameof(repairAndServices.BeginDate), "Begin date cannot be in the past.");
            }


            if (ModelState.IsValid)
            {
                try
                {
                  await _repairAndServicesRepository.UpdateAsync(repairAndServices);
                    await _repairAndServicesRepository.UpdateMechanicsAsync(repairAndServices.Id, repairAndServices.MechanicIds);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (! await _repairAndServicesRepository.ExistsAsync(repairAndServices.Id))
                    {
                        return new NotFoundViewResult("ServiceNotFound");
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
       
            return View(repairAndServices);
        }

        // GET: RepairAndServices/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new NotFoundViewResult("ServiceNotFound");
            }

            var repairAndServices = await _repairAndServicesRepository.GetWithIncludesAsync(id.Value);
            if (repairAndServices == null)
            {
                return new NotFoundViewResult("ServiceNotFound");
            }

            return View(repairAndServices);
        }

        // POST: RepairAndServices/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var result = await _repairAndServicesRepository.RemoveRepairAndServicesAsync(id);

            if (!result)
            {
                return new NotFoundViewResult("ServiceNotFound");
            }
                

            return RedirectToAction(nameof(Index));

        }



        [Authorize(Roles ="Employee,Client")]
        public async Task<IActionResult> MyServices(int? id)
        {
           var email = User.Identity.Name;


            if (this.User.IsInRole("Employee"))
            { 
                var mechanic = await  _mechanicRepository.GetByEmailAsync(email);

                if (mechanic == null)
                {
                   var services = await _repairAndServicesRepository.GetAll()
                    .Where(r => r.EndDate < DateTime.Now)
                    .Include(r => r.ServiceType)
                    .Include(r => r.Client)
                    .Include(r => r.Vehicle)
                     .ThenInclude(v => v.CarBrand)
                     .Include(r => r.Vehicle)
                     .ThenInclude(v => v.CarModel)
                    .Include(r => r.Parts)
                    .Include(r => r.Mechanics)
                    .ToListAsync();

                    if (services != null)
                    {
                        var model = new MyServicesViewModel
                        {
                            MyServices = services.ToList()
                        };

                        return View(model);
                    }
                }
                else
                {

OficinaWeb/Views/RepairAndServices/Delete.cshtml
@model OficinaWeb.Data.Entities.RepairAndServices

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>RepairAndServices</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ServiceTypeId)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ServiceType.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Mechanics)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.MechanicsNames)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Details)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Details)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Client)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Client.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Vehicle)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Vehicle.VehicleDescription)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.BeginDate)
        </dt>
        <dd class="col-sm-10">
            @Model.BeginDate.ToString("dd/MM/yyyy HH:mm")
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>
        <dd class="col-sm-10">
            @Model.EndDate.ToString("dd/MM/yyyy HH:mm")
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ServicePrice)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ServicePrice)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" />
        <a asp-action="Index" class="btn btn-outline-primary">Back to List</a>
    </form>
</div>

OficinaWeb/Views/RepairAndServices/Details.cshtml
@model OficinaWeb.Data.Entities.RepairAndServices

@{
    ViewData["Title"] = "Details";
}

<h1>Invoice</h1>

<div>
    <h4>RepairAndServices</h4>
    <hr />
  


    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ServiceTypeId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ServiceType.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Mechanics)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.MechanicsNames)
        </dd>

        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Details)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Details)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Client)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Client.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Vehicle)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Vehicle.VehicleDescription)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BeginDate)
        </dt>
        <dd class = "col-sm-10">
            @Model.BeginDate.ToString("dd/MM/yyyy HH:mm")
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>
        <dd class = "col-sm-10">
            @Model.EndDate.ToString("dd/MM/yyyy HH:mm")
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ServicePrice)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ServicePrice)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Parts)
        </dt>
        <dd class="col-sm-10">
            @if (Model.Parts != null && Model.Parts.Any())
            {
                <ul>
                    @foreach (var part in Model.Parts)
                    {
                        <li>@part.Name - @part.UnitPrice.ToString("C")</li>
                    }
                </ul>
            }
            else
            {
                <span>No parts used.</span>
			}
           
        </dd>

        <dt class="col-sm-2">
            Full Price
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.TotalPrice)
        </dd>


    </dl>
</div>
<div>
    @if (ViewData["FromMyServices"] != null && (bool)ViewData["FromMyServices"])
    {
        <a asp-action="MyServices" asp-route-id="@ViewData["VehicleId"]" class="btn btn-outline-primary">Back to Services</a>
    }
    else
    {
        <a asp-action="Index" class="btn btn-outline-primary">Back to List</a>
    }

  
</div>

OficinaWeb/Views/RepairAndServices/Index.cshtml
@model IEnumerable<OficinaWeb.Data.Entities.RepairAndServices>

@{
    ViewData["Title"] = "Index";
}

<h1>Service List</h1>

<p>
    <a asp-action="Create" class="btn btn-outline-success"> New Service</a>
</p>

<br />

<div class="table-container">
    <table class="table" id="MyTable">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.ServiceTypeId)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Mechanics)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Details)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Client)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Vehicle)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.BeginDate)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.EndDate)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ServicePrice)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
    @foreach (var item in Model) {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.ServiceType.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.MechanicsNames)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Details)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Client.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Vehicle.VehicleDescription)
                </td>
                <td>
                    @item.BeginDate.ToString("dd/MM/yyyy HH:mm")
                </td>
                <td>
                    @item.EndDate.ToString("dd/MM/yyyy HH:mm")
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ServicePrice)
                </td>
                <td>
                        <a asp-controller="Parts" asp-route-serviceId="@item.Id" class="btn btn-outline-primary">Add Parts</a>
                        <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-outline-secondary">Edit</a>
                        <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-outline-info">Invoice</a>
                        <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-outline-danger">Delete</a>
                </td>
            </tr>
    }
        </tbody>
    </table>
</div>




@section Scripts {
    <script type="text/javascript">
        $(document).ready(function () {
            $('#MyTable').DataTable({
                paging: true,
                searching: true,
                info: false,
                lengthChange: false,
                language: {
                    search: "",
                    searchPlaceholder: "Search appointments..."
                },
                dom: 'ftip'
            });
        });
    </script>
}

OficinaWeb/Views/RepairAndServices/MyServices.cshtml
@model OficinaWeb.Models.MyServicesViewModel
@{
    ViewData["Title"] = "MyServices";
}

<h1>Completed Services</h1>

@if (User.IsInRole("Client"))
{
    <a asp-controller="Vehicles"  asp-action="MyVehicles" class="btn btn-outline-primary">My Vehicles</a>
}

<div class="table-container">
    <table class="table" id="MyTable">
        <thead>
            <tr>
                <th>@Html.DisplayNameFor(model => model.MyServices.First().ServiceTypeId)</th>
                <th>@Html.DisplayNameFor(model => model.MyServices.First().Details)</th>
                <th>@Html.DisplayNameFor(model => model.MyServices.First().ClientId)</th>
                <th>@Html.DisplayNameFor(model => model.MyServices.First().VehicleId)</th>
                <th>@Html.DisplayNameFor(model => model.MyServices.First().BeginDate)</th>
                <th>@Html.DisplayNameFor(model => model.MyServices.First().EndDate)</th>
                <th>@Html.DisplayNameFor(model => model.MyServices.First().ServicePrice)</th>
                <th>@Html.DisplayNameFor(model => model.MyServices.First().Mechanics)</th>
                <th>@Html.DisplayNameFor(model => model.MyServices.First().Parts)</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.MyServices)
            {
                <tr>
                    <td>@item.ServiceType?.Name</td>
                    <td>@item.Details</td>
                    <td>@item.Client?.Name</td>
                    <td>@item.Vehicle?.VehicleDescription</td>
                    <td>@item.BeginDate.ToString("dd/MM/yyyy HH:mm")</td>
                    <td>@item.EndDate.ToString("dd/MM/yyyy HH:mm")</td>
                    <td>@item.ServicePrice</td>
                    <td>@item.MechanicsNames</td>
                    <td>@string.Join(", ", item.Parts?.Select(p => p.Name) ?? Enumerable.Empty<string>())</td>
                    <td>
                        <a asp-action="Details" asp-route-id="@item.Id" asp-route-fromMyServices="true" asp-route-vehicleId="@item.VehicleId" class="btn btn-outline-info">Invoice</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

@section Scripts {
    <script type="text/javascript">
        $(document).ready(function () {
            $('#MyTable').DataTable({
                paging: true,
                searching: true,
                info: false,
                lengthChange: false,
                language: {
                    search: "",
                    searchPlaceholder: "Search services..."
                },
                dom: 'ftip'
            });
        });
    </script>
}

OficinaWeb/Views/RepairAndServices/ServiceNotFound.cshtml
@{
    ViewData["Title"] = "ServiceNotFound";
}

<div class="container text-center d-flex flex-column justify-content-center align-items-center" style="min-height: 70vh;">
    <div>
        <h1 class="display-4 text-danger">Oops!</h1>
        <h2 class="mb-4">Service Not Found</h2>
        <p class="lead">We couldn't find the service you're looking for. It may have been removed or never existed.</p>

        <a asp-action="Index" class="btn btn-outline-primary mt-4">
            Back to Services
        </a>
    </div>
</div>